namespace Units
{
    public enum UnitLength : long
    {
        //Metric
        Meter,
        Kilometer,
        Hectometer,
        Decameter,
        Decimeter,
        Centimeter,
        Millimeter,
        //Imperial
        Thou,
        Line,
        Point,
        Foot,
        Inch,
        Palm,
        Nail,
        Finger,
        Fathom,
        Shackle,
        Mil,
        Pole,
        Hand,
        Yard,
        Chain,
        Furlong,
        Link,
        Mile,
        League,
        Cable,
        NauticalMile

    }
    public enum UnitMass
    {

        Gramm,
        Gigatonne,
        Megatonne,
        Tonne,
        Quintal,
        Kilogramm,
        Milligramm,
        Microgram,
        Nanogram,
        Picogram,
        UStonne,
        UKtonne,
        Pound,
        Ounce,
        Stone,
        Quarter,
        Hundredweight,
        Carat,
        Point

    }
    public enum UnitTime
    {
        Second,
        Millisecond,        
        Minute,
        Kilosecond,
        Hour,
        Day,
        Week,
        Megasecond
    }
    public enum UnitVolume
    {
        //Metric
        CubicMetre,
        Litre,
        Millilitre,
        CubicDecimetre,
        CubicCentimetre,
        //Imperial
        CubicFoot,
        CubicInch,
        CubicYard,
        Barrel,
        USGallon,
        Gallon,
        Cup,
        Gill,
        USPint,
        Pint,
        USQuart,
        Quart,
        USFluidOunce,
        FluidOunce,
        Peck,
        Bushel
    }
    public enum UnitArea
    {
        SquareMeter,
        SquareKilometer,
        SquareHectometer,
        SquareDecameter,
        SquareDecimeter,
        SquareCentimeter,
        SquareMillimeter,
        Hectare,
        Are,
        Centiare,
        SquareYard,
        SquareFoot,
        SquareInch,
        Perch,
        Rood,
        Acre,
        SquareMile
    }
    public enum UnitTemperature
    {
        Celsius,
        Kelvin,
        Fahrenheit,
        Rankine,
        Newton,
        Romer,
        Reaumur,
        Delisle
    }
    public enum Unit
    {
        Length,
        Mass,
        Time,
        Volume,
        Area,
        Temperature
    }
}