namespace Units
{
    public enum Length
    {
            //Metric
            Kilometer,
            Hectometer,
            Decameter,
            Meter,
            Decimeter,
            Centimeter,
            Millimeter,
        //Imperial
            Thou,
            Foot,
            Inch,
            Mil,
            Pole,
            Hand,
            Yard,
            Chain,
            Furlong,
            Link,
            Mile,
            League

        }
    public enum Mass
    {
            Gigatonne,
            Megatonne,
            Tonne,
            Kilogramm,
            Gramm,
            Milligramm,
            Microgram,
            Nanogram,
            Picogram,
            UStonne,
            UKtonne,
            Pound,
            Ounce,
        }
    public enum Time
    {
            Millisecond,
            Second,
            Minute,
            Kilosecond,
            Hour,
            Day,
            Week,
            Megasecond
    }
    public enum Volume
        {
            //Metric
            Litre,
            CubicDecimetre,
            CubicMetre,
            CubicCentimetre,
            //Imperial
            CubicFoot,
            CubicInch,
            Barrel,
            USGallon,
            USPint,
            USFluidOunce
        }
    public enum Area
        {
            SquareKilometer,
            SquareHectometer,
            SquareDecameter,
            SquareMeter,
            SquareDecimeter,
            SquareCentimeter,
            SquareMillimeter,
            Hectare,
            Are,
            Centiare,
            Perch,
            Rood,
            Acre,
            SquareMile
        }
    public enum Temperature
        {
            Celsius,
            Kelvin,
            Fahrenheit,
            Rankine,
            Newton,
            Romer,
            Reaumur,
            Delisle
        }
    public enum Quantities
    {
            Length,
            Mass,
            Time,
            Volume,
            Area,
            Temperature
        }
}